### PR TITLE
Makes Almond chat friendly to dark Gnome theme

### LINKED ISSUE #73: Create a true dark theme
I'm using Almond on latest GNOME (3.36 as of now) with Materia dark theme. I cannot see what the program writes in the window

Schermata da 2020-06-16 17-02-50

### PR DESCRIPTION
**Pull request by aurium**
almond-dark
almond-light

It changes the original approach from using an image to draw the borders to a pure CSS solution.
It solves the color change problem and can also allow a simpler responsive solution or a user themeable interface with some buttons and fields.

I can't make a identical balloon with GTK+CSS (in HTML+CSS it is possible), so I decide to propose some other changes:
* The user balloon border was changed from brown to `@theme_selected_bg_color`. That means the user balloon follows the highlight color from selected theme. I believe it is important to follow the user aesthetic preferences and be more desktop integrated.
* The background is a mix of `@theme_bg_color` and an almond inspired gradient. This will help to distinguish the balloons from the background.
* And the balloons looks nicer with a shadow.

closes #73

### CODE REVIEW

**Comment by gcampax** [comment]
This looks quite nice! Did you test non-text messages? For example, try the commands "get a dog picture" (picture message), "get xkcd" (rdl message with image), or "show me the news" (rdl message without image).

**Comment by aurium** [comment]
Ups! I totally forgot that!

**Comment by gcampax** [comment]
By the way, thanks a lot for testing the very latest version of Almond! We're preparing a new release soon, and we're grateful for any feedback ahead of it.
Did you have any comment on it, or was there anything that did not work?
(If you want and have time, you can also create an account at dev.almond.stanford.edu. From there, if you click on "enable recording", you can upvote/downvote any reply from Almond. We use that info to improve the user experience, and it's very valuable to us, especially this week as we prepare the release)

**Comment by aurium** [comment]
I don't know how to test other kinds of message, but i think if it was working with the original balloon, it will work now. The changes was pretty simple. Please @gcampax, test it in your set up, so we can be sure.

almond-pic
almond-btn

**Comment by Shresth001** [comment]
Hey, guys can you please tell me taht how can I implement this into Almond.
That would be very niece of you

**Comment by aurium** [comment]
Hey @gcampax, let me know if something is missed.

**Comment by gcampax** [comment]
Sorry, I had not a chance to test this until now. I checked the implementation, it looks good. I think the gradient is a bit too strong, but without the gradient, and just with the theme BG color, it works well both for light and dark theme. I'm going to merge this PR and then do that fix.
Thanks again for working on this!

**Pull request merged**
